version: "3"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
       -e TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - /home/malcolm/docker-storage/transmission/config:/config
      - /home/malcolm/samba/Downloads:/downloads
      - /home/malcolm/docker-storage/transmission/watch:/watch
    ports:
      - 9098:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
